### ISSUE TITLE
Images broken after 12-24 hours

### ISSUE THREAD

**Issue by RichardOzols** [chrisben/imgcache.js#100]
Using imgcache.js 0.7.6
Backbone JS based mobile app with RequireJS using latest Phonegap version.
Devices iPad Air 2, iPad 2, iPhone6, iTouch, Androids Multiple all have the same issue but the time varies.

We add custom graphics to our mobile forms and these are stored for offline use in the forms. First we make sure all images are loaded while online and after we go offline the images work fine for about 12-24 hours and the next day they don't appear at all. Persistant cache is enabled. 

Phonegap config:
```xml
<gap:plugin name="org.apache.cordova.file" />
<gap:plugin name="org.apache.cordova.file-transfer" />
<gap:plugin name="org.apache.cordova.device" />
```
Here is the code we use when an image gets rendered:
```javascript
  ImgCache.isCached(view.$el.find('img').attr('src'), function(path, success){
    if(success){
      // already cached
      ImgCache.useCachedFile(view.$el.find('img'));
    } else {
      // not there, need to cache the image
      ImgCache.cacheFile(view.$el.find('img').attr('src'), function(){
        ImgCache.useCachedFile(view.$el.find('img'));
      });
    }
  });
```
Any help is much appreciated.

**Comment by chrisben** [comment]
What version of the cordova file plugin are you using? Latest as well?
Are you sure you're not using the option "cacheClearSize" ?

**Comment by RichardOzols** [comment]
Hey - After updating all libraries and making sure everything is fired after deviceReady it seams to be working now, I am using the default options. Thank you for your input. Keep up the great work.
