### ISSUE TITLE
Cached images are getting jumbled when i try to use a custom NSURLProtocol to intercept the http requests

### ISSUE THREAD

**Issue by kalyansriram** [chrisben/imgcache.js#103]
Hi I tried to use imgcache.js for image caching in my ios cordova app and it was working fine.

But I had a requirement to write a custom http interceptor for inspecting all http requests so i created a custom NSURLProtocol implementation registered it in AppDelegate.m file like this :
    //Register the custom HttpInterceptor
    [NSURLProtocol registerClass:[HttpInterceptor class]];

But after placing this code the images are loading wrongly, I couldn't guess what could be the issue any suggestions would be helpful! Thanks

**Comment by chrisben** [comment]
ImgCache is only using the Cordova File plugin to download files, you should file an issue against this plugin instead.
Looking at [this Cordova code](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/CDVURLProtocol.m) for instance you can see it's using the same registerClass method, so I guess you're overloading cordova settings there.
