### ISSUE TITLE
Double bar on local path generates "Download error code: 1"

### ISSUE THREAD

**Issue by begrossi** [chrisben/imgcache.js#108]
I'm using the latest version of imgcache. Some images are cached ok, but other has a double bar on local path, like file:///storage/emulated/0/pertoo-cache**//**7cc3ae52582d7b9a6198cbe020346e495384e8c7.jpg.

```
ERROR: Download error source: https://pertoo-assets.s3.amazonaws.com/h/78523/newsletters/53feacc6d0b03eb42c55c7e9/bW75wbmEQjKwiMo4Y4Uw_Android%2520intro-0.jpg
ERROR: Download error target: file:///storage/emulated/0/pertoo-cache//7cc3ae52582d7b9a6198cbe020346e495384e8c7.jpg
ERROR: Download error code: 1
```

**Comment by begrossi** [comment]
I solved double bar changing getCachedFileFullPath() to:

```
    Private.getCachedFileFullPath = function (img_src) {
        var local_root = Helpers.EntryGetPath(ImgCache.attributes.dirEntry) || '';
        var name = Private.getCachedFileName(img_src);
        return local_root + ( (local_root[local_root.length-1]=='/' || name[0]=='/') ? '' : '/') + name;
    };
```

but this does not solved my problem.

**Comment by chrisben** [comment]
The url that you try to download (amazonaws.com url) is url-encoded twice (see that %2520 at the end, it is a space), that could be the problem. Try not to have spaces in your filenames.

**Comment by chrisben** [comment]
@begrossi did my answer help you fix your problem?

**Comment by chrisben** [comment]
@begrossi I am adding a kind of code similar to yours to avoid this double slash issue that has reported by someone else as well. Hopefully it will help prevent problems.
Closing this issue for now as I haven't heard from you since.
