### ISSUE TITLE
It's not working with phonegap build

### ISSUE THREAD

**Issue by tiagoporto** [chrisben/imgcache.js#113]
Hello, I'm using this with Ionic and a use phonegap to build.

I test on Chrome and works fine, when I Test the build the images the images are not displayed.

The phonegap version is 3.6.3.

I have included the settings in the config.xml.

```xml
<access origin="*"/>
<gap:plugin name="org.apache.cordova.file" />
<gap:plugin name="org.apache.cordova.device" />
<gap:plugin name="org.apache.cordova.file-transfer" />
<feature name="Device">
    <param name="ios-package" value="CDVDevice" />
    <param name="android-package" value="org.apache.cordova.device.Device" />
</feature>
<feature name="File">
    <param name="ios-package" value="CDVFile" />
    <param name="android-package" value="org.apache.cordova.file.FileUtils" />
</feature>
<feature name="FileTransfer">
    <param name="ios-package" value="CDVFileTransfer" />
    <param name="android-package" value="org.apache.cordova.filetransfer.FileTransfer" />
</feature>
```

**Comment by chrisben** [comment]
There could be many reasons you have a problem there.
I've seen you've logged an issue with angular-imgcache as well, it might be the angular part having an issue as well.
I advise you to read first the [troubleshooting section of the documentation](https://github.com/chrisben/imgcache.js#troubleshooting) to try to pinpoint your problem.

**Comment by tiagoporto** [comment]
Hello @chrisben.

Yes I'm using imgcache with angular-imgcache.js.

I tried the troubleshooting.

When I test in Chrome everything works fine.

ImgCache version 1.0rc1
Options used - Default
JS framework - Ionic - angular-imgcache.js
Environment : Cordova
Cordova version: 3.6.3
org.apache.cordova.device : 0.2.12
org.apache.cordova.file: 1.3.1
org.apache.cordova.file-transfer: 0.4.6
Nexus 4 (Android 5.0.1)
Iphone 6 (ios 8.1.3)

**Comment by chrisben** [comment]
Try to just run the examples provided with this library or the angular one and see if they work. If it works then the libraries are ok and you'll have to work out what's wrong with your code. Otherwise there's either something wrong with the configuration or a bug with a library (any one else has some feedback on cordova 3.6?).

If you get errors on both environments (iOS / android) it's likely the problem comes from your code.
Use console.log / alerts / .. anything that could help pinpoint the problem: either there's a problem during the downloading, storing or retrieving process...

**Comment by tiagoporto** [comment]
Testing in Chrome works, but in android/iOS the library does not seem to be initiated. I've done tests with various settings in phonegap and had no result.

**Comment by iVanPan** [comment]
@tiagoporto  imgcache must be uesd after deviceready is launched,in Ionic,you sholud init imgcache in  $ionicPlatform.ready() function

**Comment by tiagoporto** [comment]
@iVanPan Yes i did it right.

**Comment by chrisben** [comment]
@tiagoporto did you find anything?

**Comment by tiagoporto** [comment]
@chrisben Did not work and the functionality has been removed by the lack of time.

**Comment by chrisben** [comment]
Sorry about that.

As we don't have much information to investigate anything, I'll be closing this issue for now, reopen it if needed with more details.
