### ISSUE TITLE
Would this work for mp3's?

### ISSUE THREAD

**Issue by etiennea** [chrisben/imgcache.js#114]
Just wondering because it is called imgcache but I don't see why it wouldn't work for other types of files.

**Comment by chrisben** [comment]
Even though its main purpose is caching images for offline browsing, you can use parts of this library to store and retrieve any kind of files using the primitive methods like cacheFile and getCachedFile.
Let us know if you found some other interesting use cases.

**Comment by etiennea** [comment]
Ok thanks
