### ISSUE TITLE
[bug]iOS EntryGetPath error

### ISSUE THREAD

**Issue by maggie03230** [chrisben/imgcache.js#120]
When I download a picture with imgcache in iphone, it caught an error:
![j kpl l 7 qoe4 c 1 nbv](https://cloud.githubusercontent.com/assets/3733574/7700977/76076394-fe55-11e4-916e-4065cd5d64ed.jpg)

Then I compare the latest version with another version and found this difference:
the latest version added these lines:

if (device.platform.toLowerCase() == "ios") {
      return entry.fullPath;
}

![bfb8789f-17d7-477c-805d-e87b5737a47e](https://cloud.githubusercontent.com/assets/3733574/7701116/72f2dffc-fe56-11e4-91fb-5dcf88629c69.png)

The fullPath contains 'localhost', which causes the error.

When I note these lines, it went all well.

Hope this bug fixed soon.

**Comment by lotterfriends** [comment]
Possible solution that works for me: https://github.com/lotterfriends/imgcache.js/commit/932c96ef8cbd2f358089857050be4be4f435c601
 
tested with android 4.4.4, iOS 8 and in browser

**Comment by chrisben** [comment]
Please test 1.0rc2 and see if that fixes your problem.

**Comment by SamVerschueren** [comment]
> Please test 1.0rc2 and see if that fixes your problem.

Confirmed, it works with `1.0rc2`.
