### ISSUE TITLE
old version in Bower

### ISSUE THREAD

**Issue by blablapolicja** [chrisben/imgcache.js#129]
list of available versions in bower:

```bash
Available versions: 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0
```

why there is no `1.0rc1`?

**Comment by chrisben** [comment]
This is a release candidate, not considered as a stable release, that's why it's not on Bower.
1.0 final will be released at some point, it will then be available on bower.
