### ISSUE TITLE
[Log] ERROR: Download error code: 1 (192.168.10.1, line 28)

### ISSUE THREAD

**Issue by han4wluc** [chrisben/imgcache.js#131]
I read the docs again and again but still unable to solve this error.

    [Log] INFO: LocalFileSystem opened (192.168.10.1, line 28)
    [Log] INFO: Local cache folder opened: /imgcache/ (192.168.10.1, line 28)
    [Log] INFO: com.apple.MobileBackup metadata set (192.168.10.1, line 28)
    [Log] ERROR: Download error source: http://somename.oss-cn-hongkong.aliyuncs.com/B1yItkfhfSNm2J4 (192.168.10.1, line 28)
    [Log] ERROR: Download error target: cdvfile://localhost/root/imgcache/a916b84eefd0dc474065ea428c9bc6d27e892316 (192.168.10.1, line 28)
    [Log] ERROR: Download error code: 1 (192.168.10.1, line 28)
    
ImgCache version:
"imgcache.js": "~0.7.6",
"angular-imgcache.js": "~0.1.0"

Options used
I'm using Ionic Framework, with Angularjs. I'm not using jQuery.

Environment : Cordova 5.1.1
Plugins: 
cordova-plugin-camera 1.1.0 "Camera"
cordova-plugin-device 1.0.2-dev "Device"
cordova-plugin-file 2.0.0 "File"
cordova-plugin-file-transfer 1.2.1 "File Transfer"
cordova-plugin-geolocation 1.0.0 "Geolocation"
cordova-plugin-media 1.0.0 "Media"
cordova-plugin-media-capture 1.0.0 "Capture"

iOS version: tried on 8.2 and 8.4

Imgcache setup:
    angular.module('starter', ['ionic',
                           'ImgCache',
                           'LocalStorageModule',
                           'starter.controllers', 
                           'starter.directives', 
                           'starter.services',
                           'ngCordova'])

    .run(function($ionicPlatform, ImgCache) {
      $ionicPlatform.ready(function() {
        ImgCache.$init();
      }
    })

    .config(function($httpProvider, ImgCacheProvider) {
      ImgCacheProvider.setOptions({
        debug: true,
        usePersistentCache: true
      });
      ImgCacheProvider.manualInit = true;
    })

I tried adding deviceready listener but did not work.
document.addEventListener("deviceready", yourCallbackFunction, false);

I'm using the angular wrapper like this:
    <img img-cache ic-src="http://somename.oss-cn-hongkong.aliyuncs.com/B1yItkfhfSNm2J4"/>

My config.xml

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <widget id="com.ionicframework.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
      <name>WhosIn</name>
      <description>
            An Ionic Framework and Cordova project.
        </description>
      <author email="hi@ionicframework" href="http://ionicframework.com/">
          Ionic Framework Team
        </author>
      <content src="index.html"/>
      <access origin="*" launch-external="yes"/>
      <preference name="webviewbounce" value="false"/>
      <preference name="UIWebViewBounce" value="false"/>
      <preference name="DisallowOverscroll" value="true"/>
      <preference name="android-minSdkVersion" value="16"/>
      <preference name="BackupWebStorage" value="none"/>
      <preference name="SplashScreen" value="screen"/>
      <preference name="SplashScreenDelay" value="3000"/>
      <feature name="Device">
        <param name="ios-package" value="CDVDevice"/>
        <param name="android-package" value="org.apache.cordova.device.Device"/>
      </feature>
      <feature name="File">
        <param name="ios-package" value="CDVFile"/>
        <param name="android-package" value="org.apache.cordova.file.FileUtils"/>
      </feature>
      <feature name="FileTransfer">
        <param name="ios-package" value="CDVFileTransfer"/>
        <param name="android-package" value="org.apache.cordova.filetransfer.FileTransfer"/>
      </feature>
      <feature name="StatusBar">
        <param name="ios-package" value="CDVStatusBar" onload="true"/>
      </feature>
    ....
    </widget>

**Comment by martinjbaker** [comment]
I see the same error 1 with 0.7.6 but not with the 1.0rc1 release.

**Comment by chrisben** [comment]
I will make 1.0rc1 a final release very soon. @han4wluc please use that version in the meantime.
