### ISSUE TITLE
(SOLVED) failed to INIT  with cordova + windows phone 8.1

### ISSUE THREAD

**Issue by badpenguin** [chrisben/imgcache.js#132]
It works perfectly under android and IOS, instead when using with windows 8.1
calling .Init generate the following error inside cordova.js its catched:

Error in Success callbackId: File1541846495 : TypeError: Object doesn't support this action
Exception calling native with command :: File :: getDirectory ::exception=TypeError: Object doesn't support this action

The funny thing is that the success callback is called.

		ImgCache.init(function () {
				log_debug('ImgCache init: success!');
				self.has_image_cache = true;
			}, function () {
				log_error('ImgCache init: error! Check the log for errors');
				self.has_image_cache = false;
			});

Any idea?

**Comment by badpenguin** [comment]
FIX Your Platform Detection Routine.
This adds Nokia Lumia 630 with Windows 8.1:

   Helpers.isCordovaWindowsPhone = function () {
        log_debug('Helpers.isCordovaWindowsPhon device.platform', device.platform);
        return (Helpers.isCordova() && device && device.platform && (
            (device.platform.toLowerCase().indexOf('win32nt') >= 0) || (device.platform.toLowerCase().indexOf('windows') >= 0)
            ) );
    };

**Comment by badpenguin** [comment]
I'll test it on Windows 8.1 desktop now.

**Comment by badpenguin** [comment]
works on windows desktop too

can someone push a patch with this?

**Comment by Sturgelose** [comment]
I created a push request, as I needed this fix for myself as well. I tested it and it works :)
Seriously, making cordova/ionic with WP8.1 is hellish... 
@badpenguin, thanks for the guide that you wrote on how to setup all this :)

**Comment by chrisben** [comment]
Thanks guys!
