### ISSUE TITLE
invalidating an image

### ISSUE THREAD

**Issue by martinjbaker** [chrisben/imgcache.js#134]
readme says
>There is currently no way to invalidate single images from the cache.

but below that it says
>ImgCache.removeFile() -- removes a given file from the cache

needs updating?

**Comment by chrisben** [comment]
What I meant with this readme comment is to have a solution that would automatically expire/invalidate cached images : either depending on the HTTP response headers (_Expires_, _ETag_ ..) or just a simple rule that would define for how long images should be kept in the cache.

You can of course implement this logic yourself and use ImgCache.removeFile to remove the file from the cache.
