### ISSUE TITLE
Cached files lost on iOS after application update

### ISSUE THREAD

**Issue by typec4st** [chrisben/imgcache.js#135]
It seems like on iOS 8 (Phonegap), after updating the application, I am losing the images that I cached previously. By the way, usePersistentCache is set to true in my setup.

I'm not 100% sure as I am updating my app through Phonegap Build, but wanted to check if this is in fact the expected behavior or not. If so, is there a way to preserve the cached files after an upgrade?

Thanks

**Comment by chrisben** [comment]
It looks like the Cordova File Plugin that ImgCache uses to write images to the iOS filesystem offers an option in config.xml to define where the files should be stored and avoid this issue.
Have a look at [this page](http://makina-corpus.com/blog/metier/2014/the-right-location-for-your-cordova-app-files). If you find a solution please share it with others.

**Comment by jblok** [comment]
Changing the value of `iosPersistentFileLocation` to `Library` in config.xml, as the linked article suggests solved it for me. I also needed to update the version of imcache.js to the latest.

**Comment by chrisben** [comment]
I add this information to the CORDOVA.md documentation. Cheers.
