### ISSUE TITLE
ImgCache not loaded yet! - Have you called ImgCache.init() first?

### ISSUE THREAD

**Issue by jaypatel16** [chrisben/imgcache.js#136]
I am facing Imgcache loading issue. I have fired ImgCache.init(); on page load. My development stack is Phonegap 4.2 with jQueryMobile and Android 4.4.2 SDK. 

Error log 

INFO: ImgCache initialising
mofluid.helper-0.0.1.js:264 Store Found
mofluid.functions-0.0.1.js:406 success
mofluid.functions-0.0.1.js:407 Object
mofluid.functions-0.0.1.js:313 Images : 3
mofluid.functions-0.0.1.js:411 Success Webservice
imgcache.js:46 WARN: ImgCache not loaded yet! - Have you called ImgCache.init() first?
imgcache.js:46 INFO: LocalFileSystem opened
imgcache.js:46 INFO: Local cache folder opened: /Triveni

Observation I found is if Ajax success callback is fired before Imgcache full loading. Why Imgcache taking time to load? 

I also wanted to know if, we can delete cache images in FIFO bases?

**Comment by chrisben** [comment]
Most ImgCache functions, including Init are asynchronous, which means you can't do something like:
```
ImgCache.init();
ImgCache.cacheFile();
```

You need to use the callback provided and only once your success callback is called you can carry on with the next call.
If you don't like asynchronous calls with callbacks, try the new Promise version ['QImgCache'](https://github.com/chrisben/imgcache.js#promises).
