### ISSUE TITLE
Why is Origin not included in the http request header?

### ISSUE THREAD

**Issue by 5amfung** [chrisben/imgcache.js#137]
I noticed that request issued by imgcache does not include `Origin` in the http request header.  Is that a bug?

That's not the case for other requests generated by the angularjs app.

The lack of `Origin` in the request header is causing the server to not include `Access-Control-Allow-Origin` in the response header.  I use `django-cors-header` to handle the cors stuff.  I don't think it's an issue with the backend.  It's more a question why imgcache.js doesn't have the `Origin` in the request header like other requests?

**Comment by chrisben** [comment]
ImgCache is using the Cordova FileTransfer plugin. Try to add the _Origin_ header to  _ImgCache.options.headers_, this should work.
