### ISSUE TITLE
Flag for disable the cache for chrome

### ISSUE THREAD

**Issue by matthewthedeveloper** [chrisben/imgcache.js#140]
Would like to ask if any flag we can set to disable the cache.

Currently the cache is fine but asking for permission in chrome, so if a flag for disable the cache could be implement, we could disable the cache in chrome but leaving it enabled in other browser.

**Comment by chrisben** [comment]
If you don't want to use ImgCache for Chrome, you'll just need to avoid running ImgCache. An _if_ condition wrapped around the code calling this library should be fine. [Here's how to check if the browser is Chrome](http://stackoverflow.com/questions/4565112/javascript-how-to-find-out-if-the-user-browser-is-chrome).
