### ISSUE TITLE
FileTransfer Error on iOS

### ISSUE THREAD

**Issue by OverlappingElvis** [chrisben/imgcache.js#145]
We're using your plugin for image caching in a browser/Cordova app. We're doing an initial sync of resources (images and audio), and then caching any missing resources as needed. This is working great in browser and on our Android build, but on iOS it is throwing an error in the console for each resource that it tries to cache:

```
ERROR: Download error source: https://SERVER/media/page_images/IMAGE.jpg
ERROR: Download error target: cdvfile://localhost/root/imgcache/b6fb5f833c967309f0490c774ad6b283f45dbd00.jpg
ERROR: Download error code: 1
```

Searching for error code 1 suggests that this is an issue with writing to the local filesystem. I've made sure that we have File, FileTransfer, and Device plugins available, and have doublechecked the the file and network features are enabled. We are building this with Phonegap Build using the `cli-5.2.0 (iOS 3.9.1 / Android 4.1.1)` target. Any ideas? Thanks for a great plugin!

**Comment by OverlappingElvis** [comment]
Using v1.0rc1 seems to address this.

**Comment by webtechevolution** [comment]
Just needed to replace the following line for Store : 
store = cordova.file.dataDirectory;

and worked like a charm for me. 
Hope this helps..
