### ISSUE TITLE
problem downloading image with http redirect 302

### ISSUE THREAD

**Issue by outerbound** [chrisben/imgcache.js#147]
HI,

I am trying to do image cache for facebook profile images . Trouble is facebook profile url redirect to actual url containing the image. In chrome browser on desktop everything work fine, request follows redirect and downloads the image correctly.

When running on android or ios, I get 0 byte size image file in localCacheFolder. I know that imgcache uses  cordova file transfer plugin underneath.

Is there a way to tell cordova file transfer plugin to follow redirect when downloading or is this not supported at all?
My app is able to cache images properly when image url is direct url but failing on facebook kind profile image urls.
Using cordova version 5.2 and imgcache.js 1.0rc1

Thanks

**Comment by chrisben** [comment]
What kind of redirect is it ? do you get 301/302 response codes?
This will be a Cordova FileTransfer Plugin issue, or perhaps there's an option to enable "follow on direct" that I don't know that needs to be set..
Please test with the latest version of that plugin as [it might have a fix](https://github.com/AppGyver/steroids/issues/446) for your problem.
If not, you'll need to raise an issue with that plugin directly.

By the way there's now an rc2 version of ImgCache available.

**Comment by outerbound** [comment]
It is 302 redirect. I have tested with latest version of cordova-plugin-file-transfer. 
On android I could get going  by installing okhttp plugin, that seems to have changed urlconnection implementation underlying. No such luck on ios.

**Comment by chrisben** [comment]
I have found [this thread](https://groups.google.com/forum/#!topic/phonegap/G81rWYZqIjI) talking about your issue, they suggest using an XmlHttpRequest to get the redirect URL. You will then be able to pass that URL to ImgCache.
