### ISSUE TITLE
Problem on android 6

### ISSUE THREAD

**Issue by stormwin** [chrisben/imgcache.js#153]
Hello,

i have a problem with imgcache on my nexus 7 on Android 6.0
On imgcache.init() i got

INFO: ImgCache initialising
INFO: LocalFileSystem opened
ERROR: Failed to get/create local cache directory: 12

works well on my nexus 10 on Android 5.1.1 and huawei on Android 4.4 with same configuration

```javascript
ImgCache.options.chromeQuota = 50*1024*1024;
ImgCache.options.localCacheFolder = 'app_cache';
ImgCache.options.usePersistentCache = true;
ImgCache.options.debug = true;
```

cordova 5.4.1
cordova-android 5.0.0
using latest stable crosswalk
imgcache.js 1.0rc2

Anyone with same problem?

EDIT: This happening only on Android-sdk 23 on Android 6.0. It is not imgcache.js problem.
It's the problem with new permission system introduced in android 6.0 on sdk-23

**Comment by chrisben** [comment]
Sorry if that's not a direct code issue I will not be able to help much there. Perhaps more luck on Cordova file plugin discussion boards?

**Comment by stormwin** [comment]
Plugin has been changed since then. Now everything is ok :)
