### ISSUE TITLE
requestFileSystem is not undefined

### ISSUE THREAD

**Issue by jinsea** [chrisben/imgcache.js#157]
[INFO:CONSOLE(611)] "Uncaught TypeError: undefined is not a function", source: file:///android_asset/www/js/imgcache.js (604)

**Comment by chrisben** [comment]
I assume you're using Cordova on Android with the latest release... right?
Could you run the following anywhere at the beginning of your JS code and tell me the console output:
```
console.log('requestFileSystem', window.requestFileSystem);
```
Did you set up correctly the [Cordova file plugin](https://github.com/apache/cordova-plugin-file) ?

**Comment by jinsea** [comment]
thanks,As you say.I didn't set up correctly the plugin!!
