### ISSUE TITLE
cdvfile ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by monk-e-chops** [chrisben/imgcache.js#159]
This works in Andriod, but in chrome on Windows I am getting:

GET cdvfile://localhost/persistent/imgcache/[[base64 number]].jpg net::ERR_UNKNOWN_URL_SCHEME

and the image is not displayed.

Cordova 6.0.0 with:
cordova plugin add cordova-plugin-device

HTML:

```
<html>
    <head>
<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval'; media-src *">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">

            <h1>Hello world! 2</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>

            <div id="msg"></div>
            <img id="img" src="" />
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/jquery-2.2.0.min.js"></script>
        <script type="text/javascript" src="js/imgcache.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>
```

On **deviceready** I call **initImgCache**:

```
function go() {

    var p = 'http://192.168.69.32:8000/browser/www/img/minion.png';
    var self = this;

    ImgCache.cacheFile(p, function() {

        var element = document.getElementById('msg');
        element.innerHTML = 'cached file';

        var img = jQuery('<img />', {src: p});

        ImgCache.useCachedFile(img, function(imgsrc, fileentry) {
            var tmp = imgsrc.attr('src');

            var element = document.getElementById('msg');
            element.innerHTML = element.innerHTML +' '+ tmp;

            //$( "body" ).append(imgsrc);
            $("#img").attr('src', tmp);

            //$("#img").attr('src', "file:///localhost/persistent/imgcache/68355f631a9a1ceb3341bfe9adcf812b2623496c.jpg");
        });


    }, function() {
        // error :(
        var element = document.getElementById('msg');
        element.innerHTML = 'Error: Image failed to download';
    }, function (pe) {

    });

}

function initImgCache() {
    ImgCache.options.debug = true;
    ImgCache.options.usePersistentCache = true;
    ImgCache.init(function () {
        // alert('ImgCache init: success!');
        go();
    });
}
```

**Comment by monk-e-chops** [comment]
The problem is with this helper function:

'''
    // Fix for #42 (Cordova versions < 4.0)
    Helpers.EntryToURL = function (entry) {
        if (Helpers.isCordovaAndroidOlderThan4() && typeof entry.toNativeURL === 'function') {
            return entry.toNativeURL();
        } else if (typeof entry.toInternalURL === 'function') {
            // Fix for #97
            return entry.toInternalURL();
        } else {
            return entry.toURL();
        }
    };
'''

where in chrome on Windows Desktop with cordova 6.0.0 **return entry.toInternalURL()** gets fired BUG BUG!! It should fire: **entry.toURL()**

**Comment by monk-e-chops** [comment]
It would be worth noting in the manual that you need to enable images to be loaded from the local filesystem:

``<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval'; img-src * filesystem:; media-src *">

**Comment by chrisben** [comment]
On Chrome you shouldn't use Cordova at all: there is an implementation for the browser. Cordova is only required if you need it (i.e for mobile app targets).
If you require both with the same code (chrome+cordova), this is what I do: do not include the cordova.js file for the browser target, otherwise include it. The browser will just fail to load cordova.js but this does not break anything.

Open [index.html](https://github.com/chrisben/imgcache.js/blob/master/index.html) in your browser to see it working (without cordova included).

**Comment by monk-e-chops** [comment]
I created the project using the CLI **cordova create project** and the index.html includes `<script src="cordova.js"></script>` (as does your example) so I assume that's how most people will get their initial index.html file.

The next thing the tutorial says to do is to **cordova build browser** Then I tested the app in the browser -- the browser loads cordova.js. Then I included imgcache.js and found issues.

So it seems that the default behaviour for cordova 6.0.0 is to have a browser version of cordova.js

The browser now also fires the normal phone events most notably is the `ondeviceready`, previously in PhoneGap I had to do this:

```
if (typeof cordova !== 'undefined') {
	console.log('cordova start');
	document.addEventListener('deviceready', initImgCache, false);
} else {
	initImgCache();
}
```

This code is now not needed because **cordova** exists in the browser and `deviceready` works as normal. So including `cordova.js` in the browser seems both **expected** and **useful**.

Thanks for the amazing library, it is super useful and it has taught me a whole lot about cordova and how to write good js. Hope you don't think I'm having a moan or being mean spirited, I AM NOT! I just want to make this wonderful library _even more wonderful_!!!!! You are the best!

**Comment by chrisben** [comment]
I haven't keep up with the Cordova changes for some time. I see now what you mean.
I keep this as a TODO, and I will add this in a future release.

**Comment by FromBucketsToRainBarrels** [comment]
Hey, I get the same error. 

`cdvfile://localhost/persistent/imgcache/65e41411723b32de1e9d6e79863fbd909a3034de.png:1 GET cdvfile://localhost/persistent/imgcache/65e41411723b32de1e9d6e79863fbd909a3034de.png net::ERR_UNKNOWN_URL_SCHEME`

![image](https://cloud.githubusercontent.com/assets/22966445/23003839/4bdf7ada-f3c1-11e6-9ca5-725f6fb70d1a.png)

not sure how I can fix this. I really like you library. It would be nice if there was a fix for this using imgcachejs

**Comment by FromBucketsToRainBarrels** [comment]
![image](https://cloud.githubusercontent.com/assets/22966445/23005146/afaf6d3e-f3c8-11e6-8820-6654c76937c7.png)


I still am unable to resolve this issue on chrome.

**Comment by Maistho** [comment]
@FromBucketsToRainBarrels see #199

**Comment by olton** [comment]
Hi same error fired on Phonegap
![2017-04-22_14h19_03](https://cloud.githubusercontent.com/assets/365108/25303998/d65e7fe8-2766-11e7-8956-f2f912f4165b.png)

**Comment by Maistho** [comment]
@olton how are you serving your application?

Do you have a public repo I can check out?
