### ISSUE TITLE
cordova 6 -- Helpers.isCordova Error

### ISSUE THREAD

**Issue by monk-e-chops** [chrisben/imgcache.js#160]
The Helper function needs changing to this:

```
    Helpers.isCordova = function () {

        if (typeof cordova !== 'undefined' && cordova.platformId == 'browser')
            return false;

        return (typeof cordova !== 'undefined' || typeof phonegap !== 'undefined');
    };
```

because cordova **is** defined on the desktop (Windows Chrome)

**Comment by chrisben** [comment]
It is defined only if you load a javascript that sets it, otherwise it is undefined. You should not load cordova.js if you're running code from your browser.

**Comment by chrisben** [comment]
See my reply in #159. To be added.
