### ISSUE TITLE
Roadmap ImgCache.js for Angular 2

### ISSUE THREAD

**Issue by Sturgelose** [chrisben/imgcache.js#161]
Hi, 

As a newbie developer in Angular2, I used to use your module in Angular1/Ionic1 apps. Recently I started to move and develop in Angular2/Ionic2. Just to know, is there any plan to upgrade this module to Angular2?

Of course, thanks a lot for you hard work!

**Comment by chrisben** [comment]
ImgCache is pure javascript without dependency, it should work with any framework. I don't plan on implementing packages for different frameworks.

You might want to ask your question to the [angular-imgcache.js](https://github.com/jBenes/angular-imgcache.js/tree/master) library for the Angular1 framework.
