### ISSUE TITLE
Does it wok with lazyload?

### ISSUE THREAD

**Issue by zhouzhongyuan** [chrisben/imgcache.js#167]
If yes, what's the best practice using [lazyload](https://github.com/tuupola/jquery_lazyload/) and imgcache?

**Comment by chrisben** [comment]
I see that both lazyload and imgcache replace the source of images. 

You would need to place a call to imgcache.cacheFile within [that block of code line 106](https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js) when the image gets lazy loaded.

You could replace:

```javascript
if ($self.is("img")) {
    $self.attr("src", original);
} else {
    $self.css("background-image", "url('" + original + "')");
}
```
with something like:

```javascript
ImgCache.cacheFile(original, function () { $self.is("img") ?  ImgCache.useCachedFile($self) : ImgCache.useCachedBackground($self); });
```

Try it and that works.

**Comment by zhouzhongyuan** [comment]
Yeah, it works. Thank you.
