### ISSUE TITLE
Not allowed to load local resource problem

### ISSUE THREAD

**Issue by juniverse76** [chrisben/imgcache.js#180]
I have this problem.
It seems that the image is cached in internal directory.
But it does not get the image resource, saying "Not allowed to load local resource: file:///storage/..."

I've searched all over google and this issue...
But, I cannot find the fix for this problem.

One thing I noticed in the document was that
`If the page is opened locally (file:// ..), Chrome needs to be loaded with the following flags: --allow-file-access-from-files --allow-file-access otherwise the local filesystem will not be accessible`
I was thinking this is related issue, but I just cannot seem to understand how to add such flags.

The mobile platform is both iOS and Android,
and I'm running this library in Meteor framework.
The version is the latest version.

Please help me...

**Comment by juniverse76** [comment]
I found the solution!!!

'ImgCache.options.useDataURI = true'

I set this flag as true, and it seems to work.
Though I wish what that 'useDataURI' means...

**Comment by chrisben** [comment]
Glad you found your solution.
Here's what a [Data URI is](https://en.wikipedia.org/wiki/Data_URI_scheme).
It encodes the content of the image in base64 as a URL.
