### ISSUE TITLE
[iOS] doesn't work with nativeURLs

### ISSUE THREAD

**Issue by mixersoft** [chrisben/imgcache.js#185]
It's probably not supported, because it doesn't work with `cordova-plugin-file-transfer`

but I get this error when attempting to cache assets-library urls: 

```
[Log] ERROR: Download error source: assets-library://asset/asset.JPG?id=259E4132-F4B8-4308-B6AB-A82E79BD7375&ext=JPG
```

**Comment by chrisben** [comment]
File Transfer plugin is indeed responsible for downloading files, so if it doesn't handle it I'm afraid it won't work with imgcache either.
