### ISSUE TITLE
Use with js array of images, instead of html img src?

### ISSUE THREAD

**Issue by jamminjames** [chrisben/imgcache.js#192]
Will this work with a javascript array of images? Or is it only set up to cache images in an html gallery type situation?

**Comment by chrisben** [comment]
You can use this library how you want.
It has helper functions to cache images from an html page, but you can use it with your images in javascript via their urls.

**Comment by jamminjames** [comment]
Would that require rewriting the helper functions? If so, can you give me a hint as to how to do that?
