### ISSUE TITLE
Implement feature useCachedBackgroundWithSource 

### ISSUE THREAD

**Issue by victorivens05** [chrisben/imgcache.js#195]
Hello.

I'm using ImgCache.js and recently I was implementing it in a div with background image. Everything worked just fine, except for the fact that I needed to set the background image before use `useCachedBackground()`, and that meant another request(s), that didn't need to be done. I have some images showing at once and in an app, this requests can hurt.

For that reason I implemented by myself the method `useCachedBackgroundWithSource` in my node_modules' imgcache.js and it worked in my scenario. The question is if that's a feature worth adding, and if so, how could I pull request (i'm kinda newbie on that), or if it's needed at all, since the change was really simple.

Thanks.

**Comment by AdrianMarinica** [comment]
Hey! I created a pull request with this change, as I also needed it badly. https://github.com/chrisben/imgcache.js/pull/196

Can it be merged?
