### ISSUE TITLE
Broken images showed. the  downloaded images are of 0.0B

### ISSUE THREAD

**Issue by Sanovia** [chrisben/imgcache.js#200]
Images are downloaded but they all are empty. and broken image symbol is there.

**Comment by dengchicheng** [comment]
when I have a big image and loading, the image cache sometimes catching it as empty image, or half loaded, for example, to reproduce the issue, try to load many images with 1MB of size and during this disconnect the data.

**Comment by Sanovia** [comment]
you have to set a backup image in case images are no cached. My problem was because I was using the wrong Url, when I tried with another url everything was fine.

**Comment by AdrianMarinica** [comment]
I am closing this as it seems to not be an issue with the image cache itself.
