### ISSUE TITLE
Cant initialise ionic 2

### ISSUE THREAD

**Issue by michaeljcoyne** [chrisben/imgcache.js#203]
Inside a provider I have that gets run on platform.ready

```
 ImgCache.init(function () {
          alert('ImgCache init: success!');

      }, function () {
          alert('ImgCache init: error! Check the log for errors');
      });

```
I always get  alert('ImgCache init: error! Check the log for errors');

**Comment by ederribeiro** [comment]
Hi @michaeljcoyne!

Check this documentation: https://github.com/chrisben/imgcache.js/blob/master/CORDOVA.md

Maybe you forgot to add some plugin or permission. 
Let me know what happened  after that.

**Comment by michaeljcoyne** [comment]
I did add the file plugins and I got it to initialize but now I get 


<img width="288" alt="screen shot 2017-03-29 at 18 01 53" src="https://cloud.githubusercontent.com/assets/15672209/24468104/1065feca-14af-11e7-8664-97c9d96bbbcc.png">
