### ISSUE TITLE
v1.2.0 on NPM

### ISSUE THREAD

**Issue by jonknapp** [chrisben/imgcache.js#217]
I don't think the v1.2.0 release was ever published to NPM. Running `npm info imgcache.js` shows v1.1.1 as the latest version and `[ '1.0.0', '1.1.0', '1.1.1' ]` as the available versions.

Would someone be able to publish the latest release?

In the meantime people can install from the remote git address using something like:

`yarn add https://github.com/chrisben/imgcache.js.git#1.2.0`

**Comment by chrisben** [comment]
@chaddjohnson has rights to this npm repo.

**Comment by AdrianMarinica** [comment]
@chrisben Shouldn't we be able to push to https://www.npmjs.com/package/@chrisben/imgcache.js by updating the npm branch?

**Comment by adrianmarinica** [comment]
The project is now updated on npm. As of 1.2.0, the npm package to follow is no longer https://www.npmjs.com/package/imgcache.js , but https://www.npmjs.com/package/@chrisben/imgcache.js.
