### ISSUE TITLE
How can I see imgcache folder in android and where it gets stored in device

### ISSUE THREAD

**Issue by vivekpandey0460** [chrisben/imgcache.js#226]

**Comment by vivekpandey0460** [comment]
I am using this plug-in and it's working fine but I want to understand how and where the images get stored in android and how we can see from android file manager

**Comment by chrisben** [comment]
On Android when using Cordova, the task of writing to the filesystem is delegated to Cordova's LocalFileSystem. Depending on the options given to ImgCache, it will use a temporary storage or a persistent one.

According to [this documentation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#android-file-system-layout) you should be able to find the files within your app's folder, I guess something like:

`/data/data/<app-id>/cache/imgcache`
