### ISSUE TITLE
Access to file timestamp

### ISSUE THREAD

**Issue by natezeevo** [chrisben/imgcache.js#227]
I can see in the cache database that there is time_stamp for each file entry. Is it possible to access this?

**Comment by chrisben** [comment]
You must be talking about the hash of each filename that is used to store the cached file. It's not a timestamp.
You can retrieve this sha1 hash either by listing all cached file names within the cache folder using Cordova's FileSystem function, or you could also override the hash function ImgCache.overridables.hash to make it store the output hash into an array before returning, this way you will be able to keep track of those hashes if that's your interest.

**Comment by natezeevo** [comment]
Yes, there is a hash of the filename, but there is also a time_stamp field. I am not sure if this is part of the Cordova FileTransfer function that is accessible though?

![screen shot 2018-04-23 at 1 08 03 pm](https://user-images.githubusercontent.com/38116492/39102399-954dd920-46f7-11e8-9972-f0cb7446236f.png)

**Comment by chrisben** [comment]
This must be some internal meta data stored by Cordova. You'll have more luck looking into its documentation.
