### ISSUE TITLE
imgcache.js in error callback function return empty

### ISSUE THREAD

**Issue by ravi9376** [chrisben/imgcache.js#240]
in image cache filetransfar.download function if entrypoing is not defined then giving error 
in error block [Line no:698] there a error_callback function but they return empty so need the error in callback to define which  type of error . need to change like this.

change on line no:702 in imgcache.js
                if (error_callback) { error_callback(error); }

update.

**Comment by chrisben** [comment]
Thanks, this is now fixed in master.
