### ISSUE TITLE
Offline image file retrieving in IOS

### ISSUE THREAD

**Issue by ramtel2005** [chrisben/imgcache.js#66]
Hi,

I am using imgcache.js for storing images cached in device and retrieving those images if device is offline.

my webapp has html5 manifest caching enabled to show this app in offline mode, So imgcache.js javascript file I included in my manifest.

But I am getting error if i am offline while reading file. 
My question is: in offline mode if the page reloads, what all what all are the other javascript file i need to be place in my manifest cache.

thanks and regards,
Ramkumar P

**Comment by chrisben** [comment]
Closing this issue as I haven't heard from @ramtel2005 for a while now.
