### ISSUE TITLE
Issue with error on line 171 of FileTransfer.js

### ISSUE THREAD

**Issue by ssandison** [chrisben/imgcache.js#71]
I am using AppGyver steroids to build my app which is built on Cordova. The issue I had was:

TypeError: 'null' is not an object (evaluating 'result.lengthComputable')

I believe this is because FileEntry.toURL() is returning the full path to the file rather than something like "cdvfile://localhost/persistent/imgcache.....".

I believe it is the same error reported here:

http://stackoverflow.com/questions/23317010/cordova-file-transfer-download-result-null-error

I solved it by hacking the following function as follows:

```javascript
  // Returns the full absolute path from the root to the FileEntry
    Helpers.EntryGetPath = function (entry) {
        if (Helpers.isCordova()) {
            
	    // FIX: Path not working correctly with AppGyver Steroids
	    return 'cdvfile://localhost/' + (ImgCache.options.usePersistentCache ? 'persistent' : 'temporary') + '/' +  ImgCache.options.localCacheFolder;

	    // From Cordova 3.3 onward toURL() seems to be required instead of fullPath (#38)
            //return (typeof entry.toURL === 'function' ? Helpers.EntryToURL(entry) : entry.fullPath);
        } else {
            return entry.fullPath;
        }
    };
```

This issue is probably only affecting my set up but I thought it would be useful to share with you.

**Comment by jfrumar** [comment]
Thank you so much - this patch fixed my iOS issues in Cordova 4.2 (iOS lib 3.7.0). :+1:

**Comment by jfrumar** [comment]
I had to rollback the change to Helpers.EntryToURL because it seemed to be breaking Android (KitKat 4.4.2).

**Comment by chrisben** [comment]
@jfrumar could you please test v1.0rc1 with Android and let me know if that works, if not what should EntryToURL should be for you.
Cheers.

**Comment by chrisben** [comment]
Closing this issue because I haven't heard from you guys for a while.
