### ISSUE TITLE
Failure in getDirectory

### ISSUE THREAD

**Issue by jfrancis99** [chrisben/imgcache.js#80]
imgcache works beautifully when I test my application running under chrome, but when I install on my iOS device, it fails to initialize. 

I spent quite some time and narrowed down my problem to the "getDirectory" call in  "createCacheDir" inside the init function. The call simply never returns calls back success or failure, it doesn't do anything.

I'm on iOS 8.0.2 on an iPhone 5s and 5c
I'm using Phonegap 3.3.0 on the "appery.io" platform, so I don't have control over its versioning.
I'm using ImgCache 0.7.5-pre which seems to be the latest released version.

I've read documentation here and noticed that there were previous instances of problems in getDirectory at or subsequent to Phonegap 3.3.0 and I'm not clear on how they were solved.

I also tried to rev back to 0.7.0 which seems to be the last released version around 3.3.0 or 3.4.0 in phonegap, but same problem.

Any suggestions or help? Great piece of work, and on chrome helps immensely with speed.

**Comment by chrisben** [comment]
@jfrancis99 did you get the bottom of this issue? If not, please try v1.0rc1 to see if that version fixes your problem (includes a fix for paths for iOS).
Cheers.

**Comment by jfrancis99** [comment]
It works beautifully now - there was a mismatch in I believe JQUERY versions, and I’ve been advocating for it’s use with Appery.

Many thanks!

Joseph Francis
jdfhome@gmail.com

**Comment by jfrancis99** [comment]
It works beautifully now - there was a mismatch in I believe JQUERY versions, and I’ve been advocating for it’s use with Appery.

Many thanks!

Joseph Francis
jdfhome@gmail.com <mailto:jdfhome@gmail.com>

**Comment by chrisben** [comment]
Glad to hear it works now.
