### ISSUE TITLE
Progress Event for Imgcache

### ISSUE THREAD

**Issue by confile** [chrisben/imgcache.js#95]
Is there a way to attach a progress event when the image is going to be cached? It first has to load the image and then it has to cache it. 

I need a feedback during this process.

**Comment by chrisben** [comment]
You can use the on_progress callback of the ImgCache.cacheFile method:
```
ImgCache.cacheFile = function (img_src, success_callback, error_callback, on_progress)
```
The on_progress callback follows [this spec](http://www.w3.org/TR/2014/REC-progress-events-20140211/)  -- see #54

**Comment by confile** [comment]
thank you
